# Generated by Django 4.1.1 on 2023-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('levelname', models.CharField(max_length=32)),
                ('logname', models.CharField(db_index=True, max_length=32)),
                ('category', models.CharField(db_index=True, max_length=128)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'サーバログ',
                'verbose_name_plural': 'サーバログ',
                'get_latest_by': 'id',
            },
        ),
    ]
